package bsu.fpmi.educational_parctice2019;


import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author theme
 */

enum ButtonValues {
    button, button1, button2
}

enum LabelValues {
    label, label1, label2
}

public class MessageJPanel extends javax.swing.JPanel {
    private int key = 13;
    
    /**
     * Creates new form MessageJPanel
     */
    public MessageJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okJButton = new javax.swing.JButton();
        textJLabel = new javax.swing.JLabel();

        okJButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        okJButton.setText("OK");
        okJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okJButtonActionPerformed(evt);
            }
        });
        okJButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                okJButtonKeyTyped(evt);
            }
        });

        textJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textJLabel.setText("Текст");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(okJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(textJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(textJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(okJButton)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void okJButtonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_okJButtonKeyTyped
        if (evt.getKeyCode() == key) {
            okJButton.doClick();
        }
    }//GEN-LAST:event_okJButtonKeyTyped

    private void okJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okJButtonActionPerformed
        JOptionPane.showMessageDialog(okJButton, "Хорошего дня!!!!");
    }//GEN-LAST:event_okJButtonActionPerformed

    ButtonValues buttonValues;

    public ButtonValues getButton() {
        return buttonValues;
    }

    public void setButton(ButtonValues buttonValues) {
        this.buttonValues = buttonValues;
        
        switch (this.buttonValues) {
            case button:
                okJButton.setText("Нажмите");
                break;
            case button1:
                okJButton.setText("Клик");
                break;
            case button2:
                okJButton.setText("OK");
                break;
        }
    }
    
    LabelValues labelValues;
    
    public LabelValues getLabel() {
        return labelValues;
    }
    
    public void setLabel(LabelValues labelValues) {
        this.labelValues = labelValues;
        
        switch (this.labelValues) {
            case label:
                textJLabel.setText("Добро пожаловать");
                break;
            case label1:
                textJLabel.setText("Добрый день");
                break;
            case label2:
                textJLabel.setText("Нажмитена кнопку");
                break;
        }
    }
    
    public int getKey() {
        return key;
    }
    
    public void setKey(int key) {
        this.key = key;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton okJButton;
    private javax.swing.JLabel textJLabel;
    // End of variables declaration//GEN-END:variables
}
